<?php $this->headTitle('Home'); ?>

<div class="app">
    <div class="app-content">
        <main class="container">

            <div class="row">
                <h2><?php echo $this->redText("Hello " . $this->str)?></h2>
            </div>

        </main>
    </div>
    <footer class="app-footer">
        <div class="container">
            <hr />
            <p>
                &copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. All rights reserved.
            </p>
        </div>
    </footer>
</div>

