<?php
$this->headLink()
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css');

$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-2.1.4.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <?php echo $this->headTitle('zend-expressive')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
</head>
<body>
<?php echo $this->content ?>
<?php echo $this->inlineScript(); ?>
</body>
</html>
